load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
  name = "io_bazel_rules_dotnet",
  remote = "https://github.com/bazelbuild/rules_dotnet",
  commit = "fde72a8be291dc6927eca361ba1661f983543c2e",
  shallow_since = "1615139607 +0100"
)

load("@io_bazel_rules_dotnet//dotnet:deps.bzl", "dotnet_repositories")

dotnet_repositories()

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories_nugets", "nuget_package", "dotnet_nuget_new")

dotnet_register_toolchains()
dotnet_repositories_nugets()

### Generated by the tool
nuget_package(
    name = "fsharp.data",
    package = "fsharp.data",
    version = "4.0.1",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/FSharp.Data.dll",
        "netcoreapp2.1": "lib/netstandard2.0/FSharp.Data.dll",
        "netcoreapp2.2": "lib/netstandard2.0/FSharp.Data.dll",
        "netcoreapp3.0": "lib/netstandard2.0/FSharp.Data.dll",
        "netcoreapp3.1": "lib/netstandard2.0/FSharp.Data.dll",
    },
    core_deps = {
        "netcoreapp2.0": [
           "@fsharp.core//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@fsharp.core//:netcoreapp2.1_core",
        ],
        "netcoreapp2.2": [
           "@fsharp.core//:netcoreapp2.2_core",
        ],
        "netcoreapp3.0": [
           "@fsharp.core//:netcoreapp3.0_core",
        ],
        "netcoreapp3.1": [
           "@fsharp.core//:netcoreapp3.1_core",
        ],
    },
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/FSharp.Data.dll",
           "lib/netstandard2.0/FSharp.Data.pdb",
           "lib/netstandard2.0/FSharp.Data.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/FSharp.Data.dll",
           "lib/netstandard2.0/FSharp.Data.pdb",
           "lib/netstandard2.0/FSharp.Data.xml",
        ],
        "netcoreapp2.2": [
           "lib/netstandard2.0/FSharp.Data.dll",
           "lib/netstandard2.0/FSharp.Data.pdb",
           "lib/netstandard2.0/FSharp.Data.xml",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/FSharp.Data.dll",
           "lib/netstandard2.0/FSharp.Data.pdb",
           "lib/netstandard2.0/FSharp.Data.xml",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/FSharp.Data.dll",
           "lib/netstandard2.0/FSharp.Data.pdb",
           "lib/netstandard2.0/FSharp.Data.xml",
        ],
    },
)
nuget_package(
    name = "fsharp.core",
    package = "fsharp.core",
    version = "4.7.2",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
        "netcoreapp2.1": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
        "netcoreapp2.2": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
        "netcoreapp3.0": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
        "netcoreapp3.1": "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
    },
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
           "lib/netstandard2.0/de/FSharp.Core.resources.dll",
           "lib/netstandard2.0/es/FSharp.Core.resources.dll",
           "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/FSharp.Core.dll",
           "lib/netstandard2.0/FSharp.Core.optdata",
           "lib/netstandard2.0/FSharp.Core.sigdata",
           "lib/netstandard2.0/FSharp.Core.xml",
           "lib/netstandard2.0/it/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
           "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
           "lib/netstandard2.0/de/FSharp.Core.resources.dll",
           "lib/netstandard2.0/es/FSharp.Core.resources.dll",
           "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/FSharp.Core.dll",
           "lib/netstandard2.0/FSharp.Core.optdata",
           "lib/netstandard2.0/FSharp.Core.sigdata",
           "lib/netstandard2.0/FSharp.Core.xml",
           "lib/netstandard2.0/it/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
           "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
        ],
        "netcoreapp2.2": [
           "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
           "lib/netstandard2.0/de/FSharp.Core.resources.dll",
           "lib/netstandard2.0/es/FSharp.Core.resources.dll",
           "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/FSharp.Core.dll",
           "lib/netstandard2.0/FSharp.Core.optdata",
           "lib/netstandard2.0/FSharp.Core.sigdata",
           "lib/netstandard2.0/FSharp.Core.xml",
           "lib/netstandard2.0/it/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
           "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
           "lib/netstandard2.0/de/FSharp.Core.resources.dll",
           "lib/netstandard2.0/es/FSharp.Core.resources.dll",
           "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/FSharp.Core.dll",
           "lib/netstandard2.0/FSharp.Core.optdata",
           "lib/netstandard2.0/FSharp.Core.sigdata",
           "lib/netstandard2.0/FSharp.Core.xml",
           "lib/netstandard2.0/it/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
           "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/cs/FSharp.Core.resources.dll",
           "lib/netstandard2.0/de/FSharp.Core.resources.dll",
           "lib/netstandard2.0/es/FSharp.Core.resources.dll",
           "lib/netstandard2.0/fr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/FSharp.Core.dll",
           "lib/netstandard2.0/FSharp.Core.optdata",
           "lib/netstandard2.0/FSharp.Core.sigdata",
           "lib/netstandard2.0/FSharp.Core.xml",
           "lib/netstandard2.0/it/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ja/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ko/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pl/FSharp.Core.resources.dll",
           "lib/netstandard2.0/pt-BR/FSharp.Core.resources.dll",
           "lib/netstandard2.0/ru/FSharp.Core.resources.dll",
           "lib/netstandard2.0/tr/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hans/FSharp.Core.resources.dll",
           "lib/netstandard2.0/zh-Hant/FSharp.Core.resources.dll",
        ],
    },
)
nuget_package(
    name = "system.valuetuple",
    package = "system.valuetuple",
    version = "4.5.0",
)
nuget_package(
    name = "fparsec",
    package = "fparsec",
    version = "1.1.1",
    core_lib = {
        "netcoreapp2.0": "lib/netstandard2.0/FParsec.dll",
        "netcoreapp2.1": "lib/netstandard2.0/FParsec.dll",
        "netcoreapp2.2": "lib/netstandard2.0/FParsec.dll",
        "netcoreapp3.0": "lib/netstandard2.0/FParsec.dll",
        "netcoreapp3.1": "lib/netstandard2.0/FParsec.dll",
    },
    core_deps = {
        "netcoreapp2.0": [
           "@fsharp.core//:netcoreapp2.0_core",
        ],
        "netcoreapp2.1": [
           "@fsharp.core//:netcoreapp2.1_core",
        ],
        "netcoreapp2.2": [
           "@fsharp.core//:netcoreapp2.2_core",
        ],
        "netcoreapp3.0": [
           "@fsharp.core//:netcoreapp3.0_core",
        ],
        "netcoreapp3.1": [
           "@fsharp.core//:netcoreapp3.1_core",
        ],
    },
    core_files = {
        "netcoreapp2.0": [
           "lib/netstandard2.0/FParsec.dll",
           "lib/netstandard2.0/FParsec.pdb",
           "lib/netstandard2.0/FParsec.xml",
           "lib/netstandard2.0/FParsecCS.dll",
           "lib/netstandard2.0/FParsecCS.pdb",
           "lib/netstandard2.0/FParsecCS.xml",
        ],
        "netcoreapp2.1": [
           "lib/netstandard2.0/FParsec.dll",
           "lib/netstandard2.0/FParsec.pdb",
           "lib/netstandard2.0/FParsec.xml",
           "lib/netstandard2.0/FParsecCS.dll",
           "lib/netstandard2.0/FParsecCS.pdb",
           "lib/netstandard2.0/FParsecCS.xml",
        ],
        "netcoreapp2.2": [
           "lib/netstandard2.0/FParsec.dll",
           "lib/netstandard2.0/FParsec.pdb",
           "lib/netstandard2.0/FParsec.xml",
           "lib/netstandard2.0/FParsecCS.dll",
           "lib/netstandard2.0/FParsecCS.pdb",
           "lib/netstandard2.0/FParsecCS.xml",
        ],
        "netcoreapp3.0": [
           "lib/netstandard2.0/FParsec.dll",
           "lib/netstandard2.0/FParsec.pdb",
           "lib/netstandard2.0/FParsec.xml",
           "lib/netstandard2.0/FParsecCS.dll",
           "lib/netstandard2.0/FParsecCS.pdb",
           "lib/netstandard2.0/FParsecCS.xml",
        ],
        "netcoreapp3.1": [
           "lib/netstandard2.0/FParsec.dll",
           "lib/netstandard2.0/FParsec.pdb",
           "lib/netstandard2.0/FParsec.xml",
           "lib/netstandard2.0/FParsecCS.dll",
           "lib/netstandard2.0/FParsecCS.pdb",
           "lib/netstandard2.0/FParsecCS.xml",
        ],
    },
)
### End of generated by the tool

dotnet_nuget_new(
  name = "FParsec",
  build_file_content = """
package(default_visibility = [ "//visibility:public" ])

load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "core_import_library")

core_import_library(
  name = "FParsec.dll",
  src = "lib/netstandard2.0/FParsec.dll",
  version = "1.1.1",
)

core_import_library(
  name = "FParsecCS.dll",
  src = "lib/netstandard2.0/FParsecCS.dll",
  version = "1.1.1",
)
    """,
  package = "FParsec",
  sha256 = "0454d416c7540ed3dfdd8ed862c2071a74774b2915784e8c00ddcd447bfe4307",
  version = "1.1.1",
)
